"""The announcer's voice: every line and name from tools/voice/lines.mjs,
spoken by the Kokoro-82M speech model (Apache License 2.0), trimmed, levelled
and packed as small MP3s into src/audio/voice-clips.js.

Needs Python 3.10+ with kokoro-onnx and lameenc, and the model files from
https://github.com/thewh1teagle/kokoro-onnx/releases/tag/model-files-v1.0:

  python3 -m venv .venv && . .venv/bin/activate
  pip install kokoro-onnx lameenc
  node tools/voice/lines.mjs > tools/out/voice-lines.json
  python3 tools/voice/make-voice.py tools/out/voice-lines.json kokoro-v1.0.onnx voices-v1.0.bin

Options: --voice af_heart --speed 1.05 --kbps 32 --wav DIR (also keep WAVs).
"""
import argparse, base64, json, math, os, sys, time
import numpy as np
import lameenc
from kokoro_onnx import Kokoro

ap = argparse.ArgumentParser()
ap.add_argument('lines')
ap.add_argument('model')
ap.add_argument('voices')
ap.add_argument('--out', default=os.path.join(os.path.dirname(__file__), '../../src/audio/voice-clips.js'))
ap.add_argument('--voice', default='af_heart')
ap.add_argument('--speed', type=float, default=1.05)
ap.add_argument('--kbps', type=int, default=32)
ap.add_argument('--wav', default=None)
a = ap.parse_args()

RATE = 24000
lines = json.load(open(a.lines))
k = Kokoro(a.model, a.voices)


def db(x):
    return 20 * math.log10(max(x, 1e-9))


def tidy(x):
    """Trim the silence round a clip, fade its ends and set its level."""
    x = x.astype(np.float64)
    hop = RATE // 100  # 10 ms frames
    n = len(x) // hop
    rms = np.sqrt(np.mean(x[: n * hop].reshape(n, hop) ** 2, axis=1) + 1e-12)
    loud = rms > rms.max() * 10 ** (-40 / 20)
    idx = np.nonzero(loud)[0]
    start = max(0, idx[0] * hop - int(0.025 * RATE))
    end = min(len(x), (idx[-1] + 1) * hop + int(0.06 * RATE))
    x = x[start:end].copy()
    fi, fo = int(0.008 * RATE), int(0.03 * RATE)
    x[:fi] *= np.linspace(0, 1, fi)
    x[-fo:] *= np.linspace(1, 0, fo)
    # the same loudness for every clip: the speech itself (frames within 40 dB
    # of the loudest) at -20 dB, with the peaks kept under -1.5 dB
    m = len(x) // hop
    fr = np.sqrt(np.mean(x[: m * hop].reshape(m, hop) ** 2, axis=1) + 1e-12)
    speech = fr[fr > fr.max() * 10 ** (-40 / 20)]
    level = np.sqrt(np.mean(speech ** 2))
    x *= 10 ** (-20 / 20) / level
    peak = np.abs(x).max()
    if peak > 10 ** (-1.5 / 20):
        x *= 10 ** (-1.5 / 20) / peak
    return x


def mp3(x):
    e = lameenc.Encoder()
    e.set_bit_rate(a.kbps)
    e.set_in_sample_rate(RATE)
    e.set_channels(1)
    e.set_quality(2)
    pcm = np.clip(np.round(x * 32767), -32768, 32767).astype('<i2').tobytes()
    return e.encode(pcm) + e.flush()


if a.wav:
    import wave
    os.makedirs(a.wav, exist_ok=True)

clips, total_s, total_b = {}, 0.0, 0
t0 = time.time()
for i, ln in enumerate(lines):
    audio, sr = k.create(ln['say'], voice=a.voice, speed=a.speed, lang='en-us')
    assert sr == RATE, sr
    x = tidy(audio)
    b = mp3(x)
    clips[ln['key']] = base64.b64encode(b).decode('ascii')
    total_s += len(x) / RATE
    total_b += len(b)
    if a.wav:
        with wave.open(os.path.join(a.wav, f'{i:03d}.wav'), 'wb') as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(RATE)
            w.writeframes(np.clip(np.round(x * 32767), -32768, 32767).astype('<i2').tobytes())
    print(f"{i + 1:3d}/{len(lines)} {len(x) / RATE:4.2f} s {len(b) / 1024:4.1f} KB  {ln['key']}", flush=True)

head = (
    '// Generated by tools/voice/make-voice.py from tools/voice/lines.mjs; do not\n'
    '// edit by hand. The announcer\'s lines and the names it says after them,\n'
    f'// spoken by the Kokoro-82M speech model (voice {a.voice}, Apache License\n'
    f'// 2.0), as {RATE // 1000} kHz mono MP3s at {a.kbps} kbps in base64, filed under voiceKey().\n'
)
info = {'model': 'Kokoro-82M v1.0', 'voice': a.voice, 'speed': a.speed, 'rate': RATE, 'kbps': a.kbps, 'count': len(clips), 'seconds': round(total_s, 1)}
with open(a.out, 'w') as f:
    f.write(head)
    f.write('export const VOICE_INFO = ' + json.dumps(info) + ';\n')
    f.write('export const CLIPS = {\n')
    for key, v in clips.items():
        f.write(f'  {json.dumps(key)}: {json.dumps(v)},\n')
    f.write('};\n')
print(f'{len(clips)} clips, {total_s:.1f} s, {total_b / 1024:.0f} KB of MP3 ({os.path.getsize(a.out) / 1024:.0f} KB as text) in {time.time() - t0:.0f} s -> {a.out}')
