// Game content: fish species, legendary fish, lures, gear, hot rod parts,
// game animals and the challenge ladder.

export const FISH = {
  pink: {
    name: 'Pink Salmon',
    nick: 'Humpy',
    min: 1.2,
    max: 3.6,
    perKg: 5,
    fight: 0.55,
    jumpy: 0.35,
    shape: 'salmon',
    col: { back: 0x5a6a52, side: 0xc8ccc8, belly: 0xf2efe8, spots: 0x1a1a1a, band: null },
    info: 'The most common salmon. Males grow a big hump when spawning.',
  },
  sockeye: {
    name: 'Sockeye Salmon',
    nick: 'Red',
    min: 2,
    max: 6.5,
    perKg: 11,
    fight: 0.75,
    jumpy: 0.55,
    shape: 'salmon',
    col: { back: 0x3d6b3a, side: 0xc4261c, belly: 0xa82218, spots: null, band: null, head: 0x3d6b3a },
    info: 'Bright red in spawning colours with an olive-green head. Prized eating.',
  },
  coho: {
    name: 'Coho Salmon',
    nick: 'Silver',
    min: 3,
    max: 9.5,
    perKg: 10,
    fight: 0.85,
    jumpy: 0.75,
    shape: 'salmon',
    col: { back: 0x3a5a78, side: 0xd8dde2, belly: 0xf4f4f0, spots: 0x222222, band: null },
    info: 'Acrobatic silver fish that jumps hard when hooked.',
  },
  king: {
    name: 'King Salmon',
    nick: 'Chinook',
    min: 8,
    max: 34,
    perKg: 12,
    fight: 1.05,
    jumpy: 0.25,
    shape: 'salmon',
    col: { back: 0x44586a, side: 0xbfc4c4, belly: 0xefefe8, spots: 0x1a1a1a, band: null },
    info: 'The biggest salmon of all. Deep, powerful runs. Needs a strong rod.',
  },
  chum: {
    name: 'Chum Salmon',
    nick: 'Dog salmon',
    min: 4,
    max: 10,
    perKg: 4,
    fight: 0.85,
    jumpy: 0.2,
    shape: 'salmon',
    col: { back: 0x55604a, side: 0x9aa088, belly: 0xe0ddd0, spots: null, band: 0x7a3a8a },
    info: 'Tiger-striped purple and green bars. Tough fighters with big teeth.',
  },
  rainbow: {
    name: 'Rainbow Trout',
    nick: 'Bow',
    min: 0.5,
    max: 9,
    perKg: 14,
    fight: 0.8,
    jumpy: 0.8,
    shape: 'trout',
    col: { back: 0x4a6a3a, side: 0xc8c4a8, belly: 0xf0ece0, spots: 0x1a1a1a, band: 0xd8506a },
    info: 'Heavily spotted with a pink stripe. Alaskan leopard rainbows grow huge.',
  },
  dolly: {
    name: 'Dolly Varden',
    nick: 'Dolly',
    min: 0.4,
    max: 5,
    perKg: 9,
    fight: 0.6,
    jumpy: 0.2,
    shape: 'trout',
    col: { back: 0x3e5a5a, side: 0x9ab0a8, belly: 0xf0d8c0, spots: 0xe07a5a, band: null },
    info: 'A char with pink-orange spots. Follows the salmon to eat their eggs.',
  },
  grayling: {
    name: 'Arctic Grayling',
    nick: 'Sailfin',
    min: 0.3,
    max: 2,
    perKg: 22,
    fight: 0.5,
    jumpy: 0.4,
    shape: 'grayling',
    col: { back: 0x4a4e5a, side: 0x9a96a8, belly: 0xd8d4d0, spots: 0x1a1a2a, band: null, fin: 0x6a4a8a },
    info: 'Famous for its huge sail-like dorsal fin speckled with purple.',
  },
  char: {
    name: 'Arctic Char',
    nick: 'Char',
    min: 0.6,
    max: 9,
    perKg: 16,
    fight: 0.7,
    jumpy: 0.2,
    shape: 'trout',
    col: { back: 0x2e4a4a, side: 0xb0a080, belly: 0xe8602a, spots: 0xf0e0c0, band: null },
    info: 'Cold-water char with a fiery orange belly. Lives in deep glacial lakes.',
  },
  laker: {
    name: 'Lake Trout',
    nick: 'Laker',
    min: 2,
    max: 22,
    perKg: 7,
    fight: 0.8,
    jumpy: 0.0,
    shape: 'trout',
    col: { back: 0x4a5040, side: 0x8a8a70, belly: 0xe0dccc, spots: 0xe8e4d4, band: null },
    info: 'A big, deep-dwelling char covered in pale worm-like spots.',
  },
  pike: {
    name: 'Northern Pike',
    nick: 'Water wolf',
    min: 1,
    max: 14,
    perKg: 6,
    fight: 0.82,
    jumpy: 0.3,
    shape: 'pike',
    col: { back: 0x3a4a22, side: 0x6a8a3a, belly: 0xe8e4c0, spots: 0xe8e0a0, band: null },
    info: 'Ambush predator with a duck-bill mouth full of teeth. Loves weedy shallows.',
  },
  burbot: {
    name: 'Burbot',
    nick: 'Lush',
    min: 1,
    max: 8,
    perKg: 8,
    fight: 0.5,
    jumpy: 0.0,
    shape: 'eel',
    night: true,
    col: { back: 0x4a4230, side: 0x7a6a48, belly: 0xd0c8a8, spots: 0x2a2418, band: null },
    info: 'The only freshwater cod. A slippery night feeder with a chin barbel.',
  },
  halibut: {
    name: 'Pacific Halibut',
    nick: 'Barn door',
    min: 5,
    max: 140,
    perKg: 9,
    fight: 0.92,
    jumpy: 0.0,
    shape: 'flat',
    col: { back: 0x4a4436, side: 0x5a5242, belly: 0xf0f0ec, spots: 0x2e2a20, band: null },
    info: 'A giant flatfish with both eyes on one side. Can outweigh the angler.',
  },
  lingcod: {
    name: 'Lingcod',
    nick: 'Ling',
    min: 3,
    max: 28,
    perKg: 8,
    fight: 0.85,
    jumpy: 0.0,
    shape: 'ling',
    col: { back: 0x5a5a3a, side: 0x8a8a5a, belly: 0xd8d4b0, spots: 0x3a3a22, band: null },
    info: 'Big-mouthed rock predator. Some have blue-green flesh.',
  },
  yelloweye: {
    name: 'Yelloweye Rockfish',
    nick: 'Red snapper',
    min: 1,
    max: 8,
    perKg: 12,
    fight: 0.6,
    jumpy: 0.0,
    shape: 'rockfish',
    col: { back: 0xd0501e, side: 0xe8742a, belly: 0xf0a060, spots: null, band: null },
    info: 'Bright orange-red with golden eyes. Can live over 100 years.',
  },
  cod: {
    name: 'Pacific Cod',
    nick: 'Grey cod',
    min: 2,
    max: 12,
    perKg: 4,
    fight: 0.6,
    jumpy: 0.0,
    shape: 'cod',
    col: { back: 0x6a6450, side: 0xa09878, belly: 0xece8dc, spots: 0x4a4434, band: null },
    info: 'Brown-spotted bottom fish with a chin barbel.',
  },
};

export const SPECIES_IDS = Object.keys(FISH);

export const LEGENDS = {
  missdolly: { base: 'dolly', name: 'Miss Dolly', place: 'landing', weight: 7.4, lure: 'spinner', bonus: 900 },
  rusty: { base: 'rainbow', name: 'Rusty the Leopard', place: 'bend', weight: 12.6, lure: 'fly', bonus: 1400 },
  oldchrome: { base: 'king', name: 'Old Chrome', place: 'falls', weight: 43, lure: 'plug', bonus: 2600 },
  ghost: { base: 'char', name: 'The Ice Ghost', place: 'glacier', weight: 11.8, lure: 'fly', bonus: 1600 },
  bertha: { base: 'pike', name: 'Big Bertha', place: 'moose', weight: 19.5, lure: 'spoon', bonus: 1500 },
  barndoor: { base: 'halibut', name: 'Barn Door', place: 'pier', weight: 168, lure: 'herring', bonus: 3500 },
};

export const LURES = {
  spinner: {
    name: 'Hotrod Spinner',
    price: 0,
    desc: 'Flashy all-rounder. Trout, Dollies, grayling, pinks and silvers.',
    color: 0xd8d8d0,
    likes: {
      pink: 1.4,
      coho: 1.3,
      rainbow: 1.2,
      dolly: 1.2,
      grayling: 1.3,
      char: 1.0,
      sockeye: 0.5,
      king: 0.55,
      chum: 0.8,
      pike: 0.9,
      laker: 0.7,
      burbot: 0.3,
      halibut: 0.2,
      cod: 0.4,
      lingcod: 0.4,
      yelloweye: 0.4,
    },
  },
  fly: {
    name: 'Egg-Sucking Leech',
    price: 60,
    desc: 'Black and purple fly with a pink head. Rainbows, char and sockeye love it.',
    color: 0x3a1a4a,
    likes: {
      rainbow: 1.6,
      dolly: 1.5,
      grayling: 1.6,
      char: 1.5,
      sockeye: 1.35,
      coho: 1.0,
      pink: 0.9,
      king: 0.6,
      chum: 0.9,
      pike: 0.5,
      laker: 0.6,
      burbot: 0.4,
      halibut: 0.1,
      cod: 0.2,
      lingcod: 0.2,
      yelloweye: 0.2,
    },
  },
  spoon: {
    name: 'Flash Spoon',
    price: 90,
    desc: 'Wobbling hammered spoon. Pike, silvers, lakers and chum.',
    color: 0xe8b830,
    likes: {
      pike: 1.8,
      coho: 1.5,
      laker: 1.5,
      char: 1.3,
      chum: 1.4,
      pink: 1.2,
      king: 0.9,
      rainbow: 0.9,
      dolly: 1.0,
      sockeye: 0.5,
      grayling: 0.6,
      burbot: 0.5,
      halibut: 0.4,
      cod: 0.7,
      lingcod: 0.8,
      yelloweye: 0.7,
    },
  },
  plug: {
    name: 'Diving Plug',
    price: 180,
    desc: 'Big wobbling plug for kings and trophy fish.',
    color: 0x2aa84a,
    likes: {
      king: 2.0,
      rainbow: 1.2,
      pike: 1.35,
      coho: 1.1,
      laker: 1.2,
      chum: 1.0,
      char: 0.8,
      sockeye: 0.4,
      pink: 0.6,
      dolly: 0.7,
      grayling: 0.3,
      burbot: 0.6,
      halibut: 0.5,
      cod: 0.5,
      lingcod: 1.0,
      yelloweye: 0.6,
    },
  },
  herring: {
    name: 'Herring Jig',
    price: 220,
    desc: 'Heavy jig tipped with herring. Halibut, lingcod, rockfish and burbot.',
    color: 0xc8d8e8,
    likes: {
      halibut: 2.0,
      lingcod: 1.8,
      yelloweye: 1.7,
      cod: 1.7,
      king: 1.1,
      burbot: 1.6,
      laker: 1.0,
      char: 0.6,
      pike: 0.8,
      coho: 0.8,
      chum: 0.6,
      pink: 0.5,
      rainbow: 0.5,
      dolly: 0.7,
      grayling: 0.2,
      sockeye: 0.2,
    },
  },
};

export const RODS = [
  { id: 'classic', name: 'Hotrod Classic', price: 0, maxTension: 100, cast: 30, reel: 1.0, desc: 'Ruben’s trusty medium-action rod.' },
  { id: 'pro', name: 'Hotrod Pro', price: 650, maxTension: 150, cast: 40, reel: 1.25, desc: 'Graphite blank and a faster reel. Handles kings.' },
  {
    id: 'bigblock',
    name: 'Hotrod Big Block',
    price: 1900,
    maxTension: 235,
    cast: 52,
    reel: 1.5,
    desc: 'Heavy saltwater rig. For halibut and legendary fish.',
  },
];

export const COOLERS = [
  { cap: 8, price: 0, name: '48-quart cooler' },
  { cap: 14, price: 300, name: '120-quart cooler' },
  { cap: 24, price: 900, name: 'Chest freezer on wheels' },
];

export const ENGINES = [
  { name: 'Flathead V8', price: 0, top: 30, accel: 8.5 },
  { name: 'Small-block 350', price: 1200, top: 38, accel: 10.5 },
  { name: 'Blown big-block', price: 3500, top: 47, accel: 13 },
];

export const TIRES = [
  { name: 'Street tires', price: 0, grip: 0.62 },
  { name: 'All-terrain tires', price: 700, grip: 0.9 },
];

export const PAINTS = [
  { id: 'flame', name: 'Flame Red', price: 0, base: '#8e0f14', a: '#ffd23a', b: '#ff5a1f' },
  { id: 'black', name: 'Midnight Black', price: 400, base: '#15161a', a: '#ffcf3a', b: '#ff4a12' },
  { id: 'teal', name: 'Candy Teal', price: 400, base: '#0f6a72', a: '#ffe89a', b: '#ff8a3a' },
  { id: 'orange', name: 'Ruben Orange', price: 400, base: '#d2561a', a: '#fff0a0', b: '#ffd23a' },
];

export const GEAR = {
  scope: { name: '8x hunting scope', price: 450, desc: 'Doubles rifle zoom for long tundra shots.' },
  ammo: { name: '.30-06 cartridges (20)', price: 45, desc: 'Rifle ammunition.' },
  spray: { name: 'Bear spray', price: 80, desc: 'Stops a charging grizzly at close range. Carry up to 2.' },
  medkit: { name: 'First aid kit', price: 60, desc: 'Restores full health instantly. Carry up to 3.' },
};

export const GAME = {
  caribou: { name: 'Caribou', value: 420, hp: 110 },
  moose: { name: 'Moose', value: 900, hp: 210 },
  deer: { name: 'Sitka black-tailed deer', value: 260, hp: 80 },
  sheep: { name: 'Dall sheep', value: 650, hp: 90 },
  bear: { name: 'Grizzly bear', value: 750, hp: 240 },
  blackbear: { name: 'Black bear', value: 480, hp: 150 },
  goat: { name: 'Mountain goat', value: 560, hp: 85 },
};

export const CHALLENGES = [
  { id: 'first', text: 'Catch your first fish at Hotrod Landing', reward: 50 },
  { id: 'sell', text: 'Drive the hot rod to the Trading Post and sell your catch', reward: 75 },
  { id: 'perfect', text: 'Make a PERFECT cast (hit both marks on the meter)', reward: 60 },
  { id: 'sockeye', text: 'Catch a Sockeye Salmon at Salmon Bend', reward: 150 },
  { id: 'lure', text: 'Buy a new lure at the Trading Post', reward: 50 },
  { id: 'falls', text: 'Find Bear Falls up the River Road', reward: 100 },
  { id: 'king', text: 'Land a King Salmon over 15 kg', reward: 400 },
  { id: 'bear', text: 'Survive a grizzly charge', reward: 300 },
  { id: 'caribou', text: 'Hunt a caribou on the tundra', reward: 350 },
  { id: 'pike', text: 'Catch a Northern Pike at Moose Lake', reward: 200 },
  { id: 'char', text: 'Catch an Arctic Char at Glacier Lake', reward: 250 },
  { id: 'halibut', text: 'Catch a Pacific Halibut over 40 kg at Halibut Pier', reward: 600 },
  { id: 'moose', text: 'Hunt a moose', reward: 500 },
  { id: 'ten', text: 'Catch 10 different species', reward: 800 },
  { id: 'legend', text: 'Land a legendary fish', reward: 1500 },
  { id: 'journal', text: 'Complete the Fish Journal (all 16 species)', reward: 5000 },
];

// Fish available at a water location. Returns [{id, w}] weights.
export function speciesPool(water, world, placeId, night) {
  let pool;
  if (water.kind === 'river') {
    const s = water.s ?? 0;
    const f = world.fallsS;
    if (s < f - 25) pool = { grayling: 3, dolly: 3, char: 1.2, rainbow: 1.2 };
    else if (s < f + 140) pool = { king: 2.4, sockeye: 3, chum: 1, rainbow: 1.6, dolly: 1 };
    else if (s < world.river.length * 0.62) pool = { sockeye: 3, coho: 2.4, pink: 2, rainbow: 2, dolly: 1.4, king: 0.7 };
    else pool = { pink: 3.5, coho: 2.2, dolly: 2, chum: 1.5, king: 0.5, rainbow: 0.8 };
  } else if (water.kind === 'moose') pool = { pike: 4, rainbow: 2, laker: 1.1, grayling: 0.4, burbot: night ? 2.5 : 0.1 };
  else if (water.kind === 'glacier') pool = { char: 3, laker: 2, grayling: 1.4, dolly: 1, burbot: night ? 1 : 0 };
  else pool = { halibut: 3, cod: 2.5, yelloweye: 1.6, lingcod: 1.6, coho: 1, pink: 0.8, chum: 0.6, king: 0.4 };
  return Object.entries(pool).map(([id, w]) => ({ id, w }));
}
