// Game content: fish species, legendary fish, lures, gear, hot rod parts,
// game animals and the challenge ladder.

export const FISH = {
  pink: {
    rarity: 'common',
    name: 'Pink Salmon',
    nick: 'Humpy',
    min: 1.2,
    max: 3.6,
    perKg: 5,
    fight: 0.55,
    jumpy: 0.35,
    shape: 'salmon',
    col: { back: 0x5a6a52, side: 0xc8ccc8, belly: 0xf2efe8, spots: 0x1a1a1a, band: null },
    info: 'The most common salmon. Males grow a big hump when spawning.',
  },
  sockeye: {
    rarity: 'common',
    name: 'Sockeye Salmon',
    nick: 'Red',
    min: 2,
    max: 6.5,
    perKg: 11,
    fight: 0.75,
    jumpy: 0.55,
    shape: 'salmon',
    col: { back: 0x3d6b3a, side: 0xc4261c, belly: 0xa82218, spots: null, band: null, head: 0x3d6b3a },
    info: 'Bright red in spawning colours with an olive-green head. Prized eating.',
  },
  coho: {
    rarity: 'uncommon',
    name: 'Coho Salmon',
    nick: 'Silver',
    min: 3,
    max: 9.5,
    perKg: 10,
    fight: 0.85,
    jumpy: 0.75,
    shape: 'salmon',
    col: { back: 0x3a5a78, side: 0xd8dde2, belly: 0xf4f4f0, spots: 0x222222, band: null },
    info: 'Acrobatic silver fish that jumps hard when hooked.',
  },
  king: {
    rarity: 'rare',
    name: 'King Salmon',
    nick: 'Chinook',
    min: 8,
    max: 34,
    perKg: 12,
    fight: 1.05,
    jumpy: 0.25,
    shape: 'salmon',
    col: { back: 0x44586a, side: 0xbfc4c4, belly: 0xefefe8, spots: 0x1a1a1a, band: null },
    info: 'The biggest salmon of all. Deep, powerful runs. Needs a strong rod.',
  },
  chum: {
    rarity: 'uncommon',
    name: 'Chum Salmon',
    nick: 'Dog salmon',
    min: 4,
    max: 10,
    perKg: 4,
    fight: 0.85,
    jumpy: 0.2,
    shape: 'salmon',
    col: { back: 0x55604a, side: 0x9aa088, belly: 0xe0ddd0, spots: null, band: 0x7a3a8a },
    info: 'Tiger-striped purple and green bars. Tough fighters with big teeth.',
  },
  rainbow: {
    rarity: 'uncommon',
    name: 'Rainbow Trout',
    nick: 'Bow',
    min: 0.5,
    max: 9,
    perKg: 14,
    fight: 0.8,
    jumpy: 0.8,
    shape: 'trout',
    col: { back: 0x4a6a3a, side: 0xc8c4a8, belly: 0xf0ece0, spots: 0x1a1a1a, band: 0xd8506a },
    info: 'Heavily spotted with a pink stripe. Alaskan leopard rainbows grow huge.',
  },
  dolly: {
    rarity: 'common',
    name: 'Dolly Varden',
    nick: 'Dolly',
    min: 0.4,
    max: 5,
    perKg: 9,
    fight: 0.6,
    jumpy: 0.2,
    shape: 'trout',
    col: { back: 0x3e5a5a, side: 0x9ab0a8, belly: 0xf0d8c0, spots: 0xe07a5a, band: null },
    info: 'A char with pink-orange spots. Follows the salmon to eat their eggs.',
  },
  grayling: {
    rarity: 'common',
    name: 'Arctic Grayling',
    nick: 'Sailfin',
    min: 0.3,
    max: 2,
    perKg: 22,
    fight: 0.5,
    jumpy: 0.4,
    shape: 'grayling',
    col: { back: 0x4a4e5a, side: 0x9a96a8, belly: 0xd8d4d0, spots: 0x1a1a2a, band: null, fin: 0x6a4a8a },
    info: 'Famous for its huge sail-like dorsal fin speckled with purple.',
  },
  char: {
    rarity: 'uncommon',
    name: 'Arctic Char',
    nick: 'Char',
    min: 0.6,
    max: 9,
    perKg: 16,
    fight: 0.7,
    jumpy: 0.2,
    shape: 'trout',
    col: { back: 0x2e4a4a, side: 0xb0a080, belly: 0xe8602a, spots: 0xf0e0c0, band: null },
    info: 'Cold-water char with a fiery orange belly. Lives in deep glacial lakes.',
  },
  laker: {
    rarity: 'uncommon',
    name: 'Lake Trout',
    nick: 'Laker',
    min: 2,
    max: 22,
    perKg: 7,
    fight: 0.8,
    jumpy: 0.0,
    shape: 'trout',
    col: { back: 0x4a5040, side: 0x8a8a70, belly: 0xe0dccc, spots: 0xe8e4d4, band: null },
    info: 'A big, deep-dwelling char covered in pale worm-like spots.',
  },
  pike: {
    rarity: 'common',
    name: 'Northern Pike',
    nick: 'Water wolf',
    min: 1,
    max: 14,
    perKg: 6,
    fight: 0.82,
    jumpy: 0.3,
    shape: 'pike',
    col: { back: 0x3a4a22, side: 0x6a8a3a, belly: 0xe8e4c0, spots: 0xe8e0a0, band: null },
    info: 'Ambush predator with a duck-bill mouth full of teeth. Loves weedy shallows.',
  },
  burbot: {
    rarity: 'uncommon',
    name: 'Burbot',
    nick: 'Lush',
    min: 1,
    max: 8,
    perKg: 8,
    fight: 0.5,
    jumpy: 0.0,
    shape: 'eel',
    night: true,
    col: { back: 0x4a4230, side: 0x7a6a48, belly: 0xd0c8a8, spots: 0x2a2418, band: null },
    info: 'The only freshwater cod. A slippery night feeder with a chin barbel.',
  },
  halibut: {
    rarity: 'uncommon',
    name: 'Pacific Halibut',
    nick: 'Barn door',
    min: 5,
    max: 140,
    perKg: 9,
    fight: 0.92,
    jumpy: 0.0,
    shape: 'flat',
    col: { back: 0x4a4436, side: 0x5a5242, belly: 0xf0f0ec, spots: 0x2e2a20, band: null },
    info: 'A giant flatfish with both eyes on one side. Can outweigh the angler.',
  },
  lingcod: {
    rarity: 'uncommon',
    name: 'Lingcod',
    nick: 'Ling',
    min: 3,
    max: 28,
    perKg: 8,
    fight: 0.85,
    jumpy: 0.0,
    shape: 'ling',
    col: { back: 0x5a5a3a, side: 0x8a8a5a, belly: 0xd8d4b0, spots: 0x3a3a22, band: null },
    info: 'Big-mouthed rock predator. Some have blue-green flesh.',
  },
  yelloweye: {
    rarity: 'rare',
    name: 'Yelloweye Rockfish',
    nick: 'Red snapper',
    min: 1,
    max: 8,
    perKg: 12,
    fight: 0.6,
    jumpy: 0.0,
    shape: 'rockfish',
    col: { back: 0xd0501e, side: 0xe8742a, belly: 0xf0a060, spots: null, band: null },
    info: 'Bright orange-red with golden eyes. Can live over 100 years.',
  },
  cod: {
    rarity: 'common',
    name: 'Pacific Cod',
    nick: 'Grey cod',
    min: 2,
    max: 12,
    perKg: 4,
    fight: 0.6,
    jumpy: 0.0,
    shape: 'cod',
    col: { back: 0x6a6450, side: 0xa09878, belly: 0xece8dc, spots: 0x4a4434, band: null },
    info: 'Brown-spotted bottom fish with a chin barbel.',
  },
  steelhead: {
    rarity: 'rare',
    name: 'Steelhead',
    nick: 'Chrome',
    min: 2.5,
    max: 10,
    perKg: 16,
    fight: 0.95,
    jumpy: 0.85,
    shape: 'trout',
    col: { back: 0x3e5a6a, side: 0xd8dde0, belly: 0xf4f4f0, spots: 0x222222, band: 0xd88a96 },
    info: 'A rainbow trout that went to sea and came back chrome-bright. Blistering runs and cartwheeling jumps.',
  },
  cutthroat: {
    rarity: 'uncommon',
    name: 'Coastal Cutthroat Trout',
    nick: 'Cutty',
    min: 0.3,
    max: 3.5,
    perKg: 15,
    fight: 0.7,
    jumpy: 0.5,
    shape: 'trout',
    col: { back: 0x56663a, side: 0xc8b888, belly: 0xf0e8d0, spots: 0x1a1a1a, band: null, throat: 0xd8402a },
    info: 'Heavily spotted, with a red slash under the jaw that gives it its name. Haunts the lower river and the brackish mouth.',
  },
  whitefish: {
    rarity: 'common',
    name: 'Round Whitefish',
    nick: 'Menominee',
    min: 0.3,
    max: 2.2,
    perKg: 6,
    fight: 0.45,
    jumpy: 0.1,
    shape: 'whitefish',
    col: { back: 0x4a5a5a, side: 0xc4c8c4, belly: 0xf0f0ec, spots: null, band: null, scales: true },
    info: 'A slim silver fish with a small mouth and big scales, rooting for insects on gravel bottoms.',
  },
  kokanee: {
    rarity: 'uncommon',
    name: 'Kokanee',
    nick: 'Silver trout',
    min: 0.2,
    max: 1.6,
    perKg: 12,
    fight: 0.5,
    jumpy: 0.45,
    shape: 'salmon',
    col: { back: 0x2a4a7a, side: 0xd0d8dc, belly: 0xf4f4f0, spots: null, band: null },
    info: 'A sockeye salmon that never leaves its lake. Small, silver and blue-backed, schooling in open water.',
  },
  blackrock: {
    rarity: 'common',
    name: 'Black Rockfish',
    nick: 'Black bass',
    min: 0.5,
    max: 4.5,
    perKg: 7,
    fight: 0.62,
    jumpy: 0.05,
    shape: 'rockfish',
    col: { back: 0x25292e, side: 0x474d55, belly: 0xb8bcc0, spots: 0x16181c, band: null },
    info: 'Schools over rocky reefs and kelp near the pier and hits lures hard near the surface.',
  },
  quillback: {
    rarity: 'rare',
    name: 'Quillback Rockfish',
    nick: 'Quillback',
    min: 0.5,
    max: 3.2,
    perKg: 14,
    fight: 0.55,
    jumpy: 0,
    shape: 'quillback',
    col: { back: 0x6a4a2a, side: 0xb07a3a, belly: 0xe8c070, spots: 0xe8d060, band: null, fin: 0xe0b040 },
    info: 'Brown and orange with a tall, spiny yellow dorsal fin. Lives alone among the rocks and grows slowly.',
  },
  greenling: {
    rarity: 'common',
    name: 'Kelp Greenling',
    nick: 'Greenling',
    min: 0.4,
    max: 2,
    perKg: 8,
    fight: 0.55,
    jumpy: 0,
    shape: 'greenling',
    col: { back: 0x5a4a38, side: 0x8a7050, belly: 0xd8c8a8, spots: 0x3a7ac8, band: null },
    info: 'Males wear bright blue spots and females a freckled orange-brown. Common in the kelp by the pier.',
  },
  flounder: {
    rarity: 'uncommon',
    name: 'Starry Flounder',
    nick: 'Starry',
    min: 0.5,
    max: 4.5,
    perKg: 7,
    fight: 0.55,
    jumpy: 0,
    shape: 'flat',
    col: { back: 0x4a4232, side: 0x5a5040, belly: 0xf0ece0, spots: 0x2a2418, band: null, fin: 0xe07a20, finBars: 0x1a1612 },
    info: 'A flatfish of river mouths and estuaries, rough as sandpaper on top, with bold orange and black bars on its fins.',
  },
  sculpin: {
    rarity: 'common',
    name: 'Pacific Staghorn Sculpin',
    nick: 'Bullhead',
    min: 0.1,
    max: 0.9,
    perKg: 3,
    fight: 0.35,
    jumpy: 0,
    shape: 'sculpin',
    col: { back: 0x5a5e48, side: 0x8a8a6a, belly: 0xe0dcc0, spots: 0x2a2a20, band: null, fin: 0xc8a040 },
    info: 'Big head, wide fins and antler-like spines on its gill covers. It grunts when you lift it out.',
  },
  dogfish: {
    rarity: 'uncommon',
    name: 'Spiny Dogfish',
    nick: 'Dogfish',
    min: 1.5,
    max: 9,
    perKg: 3,
    fight: 0.75,
    jumpy: 0,
    shape: 'shark',
    col: { back: 0x585c62, side: 0x7a7e84, belly: 0xe8e8e4, spots: 0xd8dcd8, band: null },
    info: 'A small shark with a venomous spine in front of each dorsal fin. Hunts in packs along the bottom.',
  },
  skate: {
    rarity: 'epic',
    name: 'Big Skate',
    nick: 'Skate',
    min: 8,
    max: 60,
    perKg: 3.5,
    fight: 0.9,
    jumpy: 0,
    shape: 'skate',
    col: { back: 0x6a5a44, side: 0x5a4c3a, belly: 0xf0ece4, spots: 0x3a3024, band: null, eyespot: 0x2a2620 },
    info: 'A huge diamond-shaped ray that glides on the bottom, with a dark eyespot on each wing. Lifting one is like hauling up a door.',
  },
  salmonshark: {
    rarity: 'epic',
    name: 'Salmon Shark',
    nick: 'Mackerel shark',
    min: 40,
    max: 175,
    perKg: 4.5,
    fight: 1.15,
    jumpy: 0.15,
    shape: 'shark',
    col: { back: 0x2a3440, side: 0x4a5460, belly: 0xf0f0f0, spots: 0x3a3a3a, band: null, big: true },
    info: 'A warm-blooded shark that follows the salmon runs into the inlet. Blistering speed and a mouth full of teeth.',
  },
};

export const SPECIES_IDS = Object.keys(FISH);

// How often a species bites compared with others in the same water, and how
// much a kilogram of it is worth, by rarity. Legendary is for the six named
// fish.
export const RARITY = {
  common: { name: 'Common', color: 0xb8c2cc, bite: 1, value: 1 },
  uncommon: { name: 'Uncommon', color: 0x7ccf6a, bite: 0.6, value: 1.1 },
  rare: { name: 'Rare', color: 0x56a8ff, bite: 0.28, value: 1.3 },
  epic: { name: 'Epic', color: 0xc678dd, bite: 0.14, value: 1.6 },
  legendary: { name: 'Legendary', color: 0xf0b030, bite: 0, value: 1 },
};
export const RARITY_ORDER = ['common', 'uncommon', 'rare', 'epic', 'legendary'];

export const LEGENDS = {
  missdolly: { base: 'dolly', name: 'Miss Dolly', place: 'landing', weight: 7.4, lure: 'spinner', bonus: 900 },
  rusty: { base: 'rainbow', name: 'Rusty the Leopard', place: 'bend', weight: 12.6, lure: 'fly', bonus: 1400 },
  oldchrome: { base: 'king', name: 'Old Chrome', place: 'falls', weight: 43, lure: 'plug', bonus: 2600 },
  ghost: { base: 'char', name: 'The Ice Ghost', place: 'glacier', weight: 11.8, lure: 'fly', bonus: 1600 },
  bertha: { base: 'pike', name: 'Big Bertha', place: 'moose', weight: 19.5, lure: 'spoon', bonus: 1500 },
  barndoor: { base: 'halibut', name: 'Barn Door', place: 'pier', weight: 168, lure: 'herring', bonus: 3500 },
};

export const LURES = {
  spinner: {
    short: 'Spinner',
    name: 'Hotrod Spinner',
    price: 0,
    desc: 'Flashy all-rounder. Trout, Dollies, grayling, pinks and silvers.',
    color: 0xd8d8d0,
    likes: {
      pink: 1.4,
      coho: 1.3,
      rainbow: 1.2,
      dolly: 1.2,
      grayling: 1.3,
      char: 1.0,
      sockeye: 0.5,
      king: 0.55,
      chum: 0.8,
      pike: 0.9,
      laker: 0.7,
      burbot: 0.3,
      halibut: 0.2,
      cod: 0.4,
      lingcod: 0.4,
      yelloweye: 0.4,
      steelhead: 1.1,
      cutthroat: 1.4,
      whitefish: 0.8,
      kokanee: 1.4,
      blackrock: 1.0,
      quillback: 0.5,
      greenling: 0.7,
      flounder: 0.3,
      sculpin: 0.6,
      dogfish: 0.3,
      skate: 0.1,
      salmonshark: 0.3,
    },
  },
  fly: {
    short: 'Leech',
    name: 'Egg-Sucking Leech',
    price: 60,
    desc: 'Black and purple fly with a pink head. Rainbows, char and sockeye love it.',
    color: 0x3a1a4a,
    likes: {
      rainbow: 1.6,
      dolly: 1.5,
      grayling: 1.6,
      char: 1.5,
      sockeye: 1.35,
      coho: 1.0,
      pink: 0.9,
      king: 0.6,
      chum: 0.9,
      pike: 0.5,
      laker: 0.6,
      burbot: 0.4,
      halibut: 0.1,
      cod: 0.2,
      lingcod: 0.2,
      yelloweye: 0.2,
      steelhead: 1.5,
      cutthroat: 1.5,
      whitefish: 1.0,
      kokanee: 0.8,
      blackrock: 0.3,
      quillback: 0.2,
      greenling: 0.3,
      flounder: 0.2,
      sculpin: 0.5,
      dogfish: 0.1,
      skate: 0.05,
      salmonshark: 0.05,
    },
  },
  spoon: {
    short: 'Spoon',
    name: 'Flash Spoon',
    price: 90,
    desc: 'Wobbling hammered spoon. Pike, silvers, lakers and chum.',
    color: 0xe8b830,
    likes: {
      pike: 1.8,
      coho: 1.5,
      laker: 1.5,
      char: 1.3,
      chum: 1.4,
      pink: 1.2,
      king: 0.9,
      rainbow: 0.9,
      dolly: 1.0,
      sockeye: 0.5,
      grayling: 0.6,
      burbot: 0.5,
      halibut: 0.4,
      cod: 0.7,
      lingcod: 0.8,
      yelloweye: 0.7,
      steelhead: 1.0,
      cutthroat: 1.2,
      whitefish: 0.6,
      kokanee: 1.3,
      blackrock: 1.3,
      quillback: 0.8,
      greenling: 0.9,
      flounder: 0.4,
      sculpin: 0.5,
      dogfish: 0.6,
      skate: 0.2,
      salmonshark: 0.8,
    },
  },
  plug: {
    short: 'Plug',
    name: 'Diving Plug',
    price: 180,
    desc: 'Big wobbling plug for kings and trophy fish.',
    color: 0x2aa84a,
    likes: {
      king: 2.0,
      rainbow: 1.2,
      pike: 1.35,
      coho: 1.1,
      laker: 1.2,
      chum: 1.0,
      char: 0.8,
      sockeye: 0.4,
      pink: 0.6,
      dolly: 0.7,
      grayling: 0.3,
      burbot: 0.6,
      halibut: 0.5,
      cod: 0.5,
      lingcod: 1.0,
      yelloweye: 0.6,
      steelhead: 1.3,
      cutthroat: 0.9,
      whitefish: 0.2,
      kokanee: 0.5,
      blackrock: 1.0,
      quillback: 0.7,
      greenling: 0.7,
      flounder: 0.3,
      sculpin: 0.4,
      dogfish: 0.5,
      skate: 0.3,
      salmonshark: 1.1,
    },
  },
  herring: {
    short: 'Herring Jig',
    name: 'Herring Jig',
    price: 220,
    desc: 'Heavy jig tipped with herring. Halibut, lingcod, rockfish and burbot.',
    color: 0xc8d8e8,
    likes: {
      halibut: 2.0,
      lingcod: 1.8,
      yelloweye: 1.7,
      cod: 1.7,
      king: 1.1,
      burbot: 1.6,
      laker: 1.0,
      char: 0.6,
      pike: 0.8,
      coho: 0.8,
      chum: 0.6,
      pink: 0.5,
      rainbow: 0.5,
      dolly: 0.7,
      grayling: 0.2,
      sockeye: 0.2,
      steelhead: 0.4,
      cutthroat: 0.8,
      whitefish: 0.2,
      kokanee: 0.3,
      blackrock: 1.5,
      quillback: 1.6,
      greenling: 1.4,
      flounder: 1.3,
      sculpin: 1.5,
      dogfish: 1.8,
      skate: 1.6,
      salmonshark: 1.4,
    },
  },
  bead: {
    short: 'Glo Bead',
    name: 'Glo Bead',
    price: 45,
    desc: 'A single orange bead that drifts like a salmon egg. Dollies, rainbows, char and steelhead cannot resist it.',
    color: 0xff8a3a,
    likes: {
      dolly: 2.0,
      rainbow: 1.7,
      char: 1.7,
      steelhead: 1.8,
      cutthroat: 1.5,
      grayling: 1.3,
      whitefish: 1.4,
      kokanee: 0.9,
      sockeye: 0.8,
      coho: 0.7,
      pink: 0.8,
      king: 0.6,
      chum: 0.7,
      laker: 0.6,
      pike: 0.2,
      burbot: 0.5,
      halibut: 0.1,
      cod: 0.15,
      lingcod: 0.15,
      yelloweye: 0.1,
      blackrock: 0.2,
      quillback: 0.1,
      greenling: 0.2,
      flounder: 0.2,
      sculpin: 0.3,
      dogfish: 0.1,
      skate: 0.05,
      salmonshark: 0.05,
    },
  },
  dryfly: {
    short: 'Dry Fly',
    name: 'Mosquito Dry Fly',
    price: 50,
    desc: 'A tiny grey fly that floats on the surface. Grayling rise to it, and so do trout and whitefish.',
    color: 0x8a8a7a,
    likes: {
      grayling: 2.2,
      rainbow: 1.4,
      cutthroat: 1.6,
      whitefish: 1.6,
      char: 1.1,
      dolly: 1.0,
      kokanee: 1.1,
      steelhead: 0.6,
      pink: 0.4,
      sockeye: 0.3,
      coho: 0.5,
      king: 0.1,
      chum: 0.2,
      pike: 0.3,
      laker: 0.3,
      burbot: 0.05,
      halibut: 0.05,
      cod: 0.05,
      lingcod: 0.05,
      yelloweye: 0.05,
      blackrock: 0.05,
      quillback: 0.05,
      greenling: 0.05,
      flounder: 0.05,
      sculpin: 0.05,
      dogfish: 0.05,
      skate: 0.05,
      salmonshark: 0.05,
    },
  },
  bugger: {
    short: 'Bugger',
    name: 'Woolly Bugger',
    price: 70,
    desc: 'An olive streamer that swims like a leech or a small fish. Rainbows, steelhead, cutthroat and silvers chase it.',
    color: 0x4a5a2a,
    likes: {
      rainbow: 1.7,
      steelhead: 1.6,
      cutthroat: 1.6,
      coho: 1.4,
      dolly: 1.3,
      char: 1.3,
      laker: 1.0,
      pike: 1.1,
      grayling: 1.0,
      sockeye: 0.9,
      pink: 1.0,
      king: 0.8,
      chum: 1.0,
      kokanee: 0.9,
      whitefish: 0.8,
      burbot: 0.8,
      halibut: 0.2,
      cod: 0.3,
      lingcod: 0.4,
      yelloweye: 0.3,
      blackrock: 0.7,
      quillback: 0.3,
      greenling: 0.6,
      flounder: 0.3,
      sculpin: 0.8,
      dogfish: 0.2,
      skate: 0.05,
      salmonshark: 0.1,
    },
  },
  popper: {
    short: 'Popper',
    name: 'Pike Popper',
    price: 120,
    desc: 'A frog-shaped lure that pops and splashes across the lily pads. Pike explode on it.',
    color: 0x6a9a2a,
    likes: {
      pike: 2.4,
      laker: 0.4,
      rainbow: 0.7,
      coho: 0.5,
      cutthroat: 0.6,
      grayling: 0.3,
      char: 0.3,
      dolly: 0.3,
      steelhead: 0.3,
      sockeye: 0.1,
      pink: 0.3,
      king: 0.2,
      chum: 0.2,
      kokanee: 0.3,
      whitefish: 0.1,
      burbot: 0.05,
      blackrock: 0.6,
      halibut: 0.1,
      cod: 0.15,
      lingcod: 0.15,
      yelloweye: 0.1,
      quillback: 0.1,
      greenling: 0.2,
      flounder: 0.2,
      sculpin: 0.3,
      dogfish: 0.1,
      skate: 0.05,
      salmonshark: 0.05,
    },
  },
  hoochie: {
    short: 'Hoochie',
    name: 'Octopus Hoochie',
    price: 150,
    desc: 'A pink squid skirt behind a flashing dodger, the classic salmon trolling rig. Kings, silvers and chum, and even sharks.',
    color: 0xe05a9a,
    likes: {
      king: 2.0,
      coho: 1.8,
      chum: 1.7,
      pink: 1.6,
      sockeye: 0.9,
      steelhead: 0.7,
      cutthroat: 0.6,
      rainbow: 0.6,
      dolly: 0.6,
      char: 0.7,
      laker: 0.9,
      pike: 0.6,
      kokanee: 0.8,
      grayling: 0.2,
      whitefish: 0.2,
      burbot: 0.3,
      salmonshark: 1.5,
      dogfish: 1.0,
      halibut: 0.8,
      lingcod: 0.8,
      blackrock: 1.2,
      quillback: 0.6,
      greenling: 0.5,
      yelloweye: 0.5,
      cod: 0.6,
      flounder: 0.3,
      sculpin: 0.4,
      skate: 0.2,
    },
  },
  swimbait: {
    short: 'Swimbait',
    name: 'Paddle-tail Swimbait',
    price: 110,
    desc: 'A soft plastic herring with a kicking tail. Lingcod, rockfish, greenling and pike smash it.',
    color: 0x9ab0c8,
    likes: {
      lingcod: 1.9,
      blackrock: 2.0,
      quillback: 1.5,
      greenling: 1.6,
      yelloweye: 1.4,
      cod: 1.3,
      halibut: 1.3,
      sculpin: 1.3,
      pike: 1.6,
      laker: 1.3,
      coho: 1.1,
      king: 0.9,
      rainbow: 0.9,
      steelhead: 0.8,
      dogfish: 0.9,
      salmonshark: 0.7,
      flounder: 0.8,
      skate: 0.4,
      char: 0.8,
      dolly: 0.6,
      cutthroat: 0.8,
      chum: 0.7,
      pink: 0.7,
      sockeye: 0.3,
      kokanee: 0.5,
      grayling: 0.3,
      whitefish: 0.2,
      burbot: 0.7,
    },
  },
  squid: {
    short: 'Squid',
    name: 'Circle Hook and Squid',
    price: 160,
    desc: 'A whole squid on a big circle hook, fished on the bottom. Halibut, skates, dogfish, flounder and sculpins.',
    color: 0xe8d8c8,
    likes: {
      halibut: 2.2,
      skate: 2.4,
      dogfish: 2.2,
      flounder: 2.0,
      sculpin: 1.8,
      cod: 1.8,
      lingcod: 1.2,
      yelloweye: 1.2,
      quillback: 1.1,
      greenling: 1.0,
      blackrock: 0.8,
      salmonshark: 1.2,
      burbot: 1.4,
      laker: 0.9,
      char: 0.6,
      pike: 0.6,
      king: 0.5,
      coho: 0.3,
      chum: 0.3,
      pink: 0.3,
      sockeye: 0.1,
      rainbow: 0.3,
      dolly: 0.4,
      steelhead: 0.2,
      cutthroat: 0.3,
      kokanee: 0.1,
      grayling: 0.1,
      whitefish: 0.2,
    },
  },
};

export const RODS = [
  { id: 'classic', name: 'Hotrod Classic', price: 0, maxTension: 100, cast: 30, reel: 1.0, desc: 'Ruben’s trusty medium-action rod.' },
  { id: 'pro', name: 'Hotrod Pro', price: 650, maxTension: 150, cast: 40, reel: 1.25, desc: 'Graphite blank and a faster reel. Handles kings.' },
  {
    id: 'bigblock',
    name: 'Hotrod Big Block',
    price: 1900,
    maxTension: 235,
    cast: 52,
    reel: 1.5,
    desc: 'Heavy saltwater rig. For halibut and legendary fish.',
  },
];

// The timing bar of the cast, laid out like a player's own drawing of it: a
// white marker sweeps left to right over red, orange and green with a dark
// green line in the middle. Half-widths from the middle, in bar widths: the
// line is a perfect cast, green lands where the throw line shows, orange
// hooks it left or slices it right, and red is a backlash. speed is bar
// widths a second.
export const TIMING = { speed: 0.9, perfect: 0.025, green: 0.125, orange: 0.355 };

// The timing bar as a CSS background, from the same zones the cast uses.
export function timingGradient(T = TIMING) {
  const zones = [
    ['#f0261a', 0, 0.5 - T.orange],
    ['#ff8a00', 0.5 - T.orange, 0.5 - T.green],
    ['#2fe02a', 0.5 - T.green, 0.5 - T.perfect],
    ['#0c5a12', 0.5 - T.perfect, 0.5 + T.perfect],
    ['#2fe02a', 0.5 + T.perfect, 0.5 + T.green],
    ['#ff8a00', 0.5 + T.green, 0.5 + T.orange],
    ['#f0261a', 0.5 + T.orange, 1],
  ];
  return `linear-gradient(90deg, ${zones.map(([c, a, b]) => `${c} ${(a * 100).toFixed(1)}% ${(b * 100).toFixed(1)}%`).join(', ')})`;
}

export const COOLERS = [
  { cap: 8, price: 0, name: '48-quart cooler' },
  { cap: 14, price: 300, name: '120-quart cooler' },
  { cap: 24, price: 900, name: 'Chest freezer on wheels' },
];

export const ENGINES = [
  { name: 'Flathead V8', price: 0, top: 30, accel: 8.5 },
  { name: 'Small-block 350', price: 1200, top: 38, accel: 10.5 },
  { name: 'Blown big-block', price: 3500, top: 47, accel: 13 },
];

export const TIRES = [
  { name: 'Street tires', price: 0, grip: 0.62 },
  { name: 'All-terrain tires', price: 700, grip: 0.9 },
];

export const PAINTS = [
  { id: 'flame', name: 'Flame Red', price: 0, base: '#8e0f14', a: '#ffd23a', b: '#ff5a1f' },
  { id: 'black', name: 'Midnight Black', price: 400, base: '#15161a', a: '#ffcf3a', b: '#ff4a12' },
  { id: 'teal', name: 'Candy Teal', price: 400, base: '#0f6a72', a: '#ffe89a', b: '#ff8a3a' },
  { id: 'orange', name: 'Ruben Orange', price: 400, base: '#d2561a', a: '#fff0a0', b: '#ffd23a' },
];

// arrows the quiver holds
export const QUIVER = 36;

export const GEAR = {
  arrows: { name: 'Cedar arrows (12)', price: 40, desc: 'Broadhead arrows for the longbow. Walk over the ones that miss to pick them up.' },
  sight: { name: 'Bow sight and stabiliser', price: 450, desc: 'A steadier hold at full draw and a closer look when you AIM.' },
  yew: { name: 'Yew longbow', price: 700, desc: 'A heavier draw: faster, flatter arrows that hit harder.' },
  spray: { name: 'Bear spray', price: 80, desc: 'Stops a charging grizzly at close range. Carry up to 2.' },
  medkit: { name: 'First aid kit', price: 60, desc: 'Restores full health instantly. Carry up to 3.' },
};

export const GAME = {
  caribou: { name: 'Caribou', value: 420, hp: 110 },
  moose: { name: 'Moose', value: 900, hp: 210 },
  deer: { name: 'Sitka black-tailed deer', value: 260, hp: 80 },
  sheep: { name: 'Dall sheep', value: 650, hp: 90 },
  bear: { name: 'Grizzly bear', value: 750, hp: 240 },
  blackbear: { name: 'Black bear', value: 480, hp: 150 },
  goat: { name: 'Mountain goat', value: 560, hp: 85 },
};

export const CHALLENGES = [
  { id: 'first', text: 'Catch your first fish at Hotrod Landing', reward: 50 },
  { id: 'sell', text: 'Drive the hot rod to the Trading Post and sell your catch', reward: 75 },
  { id: 'perfect', text: 'Make a PERFECT cast (hit both marks on the meter)', reward: 60 },
  { id: 'sockeye', text: 'Catch a Sockeye Salmon at Salmon Bend', reward: 150 },
  { id: 'lure', text: 'Buy a new lure at the Trading Post', reward: 50 },
  { id: 'falls', text: 'Find Bear Falls up the River Road', reward: 100 },
  { id: 'king', text: 'Land a King Salmon over 15 kg', reward: 400 },
  { id: 'bear', text: 'Survive a grizzly charge', reward: 300 },
  { id: 'caribou', text: 'Hunt a caribou on the tundra', reward: 350 },
  { id: 'pike', text: 'Catch a Northern Pike at Moose Lake', reward: 200 },
  { id: 'char', text: 'Catch an Arctic Char at Glacier Lake', reward: 250 },
  { id: 'halibut', text: 'Catch a Pacific Halibut over 40 kg at Halibut Pier', reward: 600 },
  { id: 'moose', text: 'Hunt a moose', reward: 500 },
  { id: 'ten', text: 'Catch 10 different species', reward: 800 },
  { id: 'rare', text: 'Catch a Rare fish (steelhead, king salmon, yelloweye or quillback rockfish)', reward: 450 },
  { id: 'twenty', text: 'Catch 20 different species', reward: 1600 },
  { id: 'epic', text: 'Catch an Epic fish: a big skate or a salmon shark at Halibut Pier', reward: 1400 },
  { id: 'legend', text: 'Land a legendary fish', reward: 1500 },
  { id: 'journal', text: 'Complete the Fish Journal (all 28 species)', reward: 5000 },
];

// Fish available at a water location. Returns [{id, w}] weights: how well
// the water suits each species, times how rare the species is.
export function speciesPool(water, world, placeId, night) {
  let pool;
  if (water.kind === 'river') {
    const s = water.s ?? 0;
    const f = world.fallsS;
    const L = world.river.length;
    if (s < f - 25) pool = { grayling: 3, dolly: 3, whitefish: 2.5, char: 1.5, rainbow: 1.5 };
    else if (s < f + 140) pool = { sockeye: 3, king: 2.4, chum: 1.2, rainbow: 1.6, dolly: 1, steelhead: 1.2 };
    else if (s < L * 0.62) pool = { sockeye: 3, coho: 2.4, pink: 2, rainbow: 2, dolly: 1.4, king: 0.8, steelhead: 1.4, cutthroat: 0.8 };
    else {
      pool = { pink: 3.5, coho: 2.2, dolly: 2, chum: 1.5, king: 0.6, rainbow: 0.8, cutthroat: 2.2, steelhead: 1 };
      // the brackish mouth brings in flounder and sculpins
      if (s > L * 0.9) Object.assign(pool, { flounder: 1.6, sculpin: 1.2 });
    }
  } else if (water.kind === 'moose') pool = { pike: 4, rainbow: 2, kokanee: 2.6, laker: 1.1, grayling: 0.4, burbot: night ? 2.5 : 0.1 };
  else if (water.kind === 'glacier') pool = { char: 3, laker: 2, whitefish: 2.5, grayling: 1.4, dolly: 1, burbot: night ? 1 : 0 };
  else
    pool = {
      halibut: 3,
      cod: 2.5,
      blackrock: 3,
      greenling: 2.5,
      sculpin: 2,
      flounder: 1.2,
      dogfish: 1.6,
      yelloweye: 1.6,
      quillback: 1.4,
      lingcod: 1.6,
      coho: 1,
      pink: 0.8,
      chum: 0.6,
      king: 0.4,
      skate: 1.4,
      salmonshark: 0.7,
    };
  return Object.entries(pool).map(([id, w]) => ({ id, w: w * RARITY[FISH[id].rarity].bite }));
}
