// Science objectives: things to see, do and find out about all over Kenai
// Country, from the craters of the Moon to the granite of the tors. They
// run beside the challenges (any order, all at once) and each one, done,
// keeps what you learned in the Journal's Science page. Each has a field,
// a short title, what to do (with where), what you learn, a reward, and a
// test on the game's events (see GameState.event).
export const FIELDS = {
  astronomy: 'Astronomy',
  physics: 'Physics and engineering',
  earth: 'Earth science',
  biology: 'Biology',
  life: 'Life beyond Earth',
};

const PLANETS = ['mercury', 'venus', 'mars', 'jupiter', 'saturn'];
const SALMON = ['sockeye', 'king', 'coho', 'pink', 'chum'];

export const SCIENCE = [
  // ------------------------------------------------------------ astronomy
  {
    id: 'moon',
    field: 'astronomy',
    title: 'Craters on the Moon',
    text: 'Look at the Moon through the telescope at the Tundra Observatory',
    learn: 'The craters are scars of asteroids and comets that hit the Moon. With no air or water to wear them away they last for billions of years; the dark plains are old lava flows.',
    reward: 120,
    test: (e) => e.type === 'scope' && e.id === 'moon',
  },
  {
    id: 'planet',
    field: 'astronomy',
    title: "A planet's disc",
    text: 'See a planet through the telescope (it finds the bright ones in daylight too)',
    learn: 'Planets shine by sunlight they reflect, and a telescope shows each one as a little disc. Stars stay points of light however much you magnify them: they are much too far away.',
    reward: 150,
    test: (e) => e.type === 'scope' && PLANETS.includes(e.id),
  },
  {
    id: 'galaxy',
    field: 'astronomy',
    title: 'Another galaxy',
    text: 'Find the Andromeda Galaxy (M31) through the telescope on a dark night',
    learn: 'The light you see left Andromeda about 2.5 million years ago, before there were people. It is a spiral of hundreds of billions of stars, and it is coming toward our own galaxy, the Milky Way.',
    reward: 200,
    test: (e) => e.type === 'scope' && e.id === 'm31',
  },
  {
    id: 'pulsar',
    field: 'astronomy',
    title: "A dead star's heartbeat",
    text: "Listen to a pulsar with the observatory's radio dish",
    learn: 'A pulsar is the core left when a big star explodes: a ball of neutrons about 20 km across, spinning, sweeping a beam of radio waves past the Earth like a lighthouse, from about once a second to hundreds of times a second.',
    reward: 180,
    test: (e) => e.type === 'radio' && e.id === 'pulsar',
  },
  {
    id: 'cmb',
    field: 'astronomy',
    title: "The Big Bang's afterglow",
    text: 'Tune the radio dish to the cosmic microwave background',
    learn: 'Microwaves from when the universe was 380,000 years old fill the whole sky. The universe has stretched so much since that they have cooled to 2.7 degrees above absolute zero.',
    reward: 220,
    test: (e) => e.type === 'radio' && e.id === 'cmb',
  },
  {
    id: 'iss',
    field: 'astronomy',
    title: 'A station in orbit',
    text: 'Watch the International Space Station pass over (the observatory board knows when)',
    learn: 'The station goes round the Earth about every 90 minutes, 400 km up. It is falling all the time, but moving sideways so fast, 7.7 km a second, that it keeps missing the ground.',
    reward: 150,
    test: (e) => e.type === 'iss',
  },
  {
    id: 'aurora',
    field: 'astronomy',
    title: 'The northern lights',
    text: 'See the aurora: a clear night, away from lights, looking north',
    learn: "Particles from the Sun, steered by the Earth's magnetic field, rain into the air 100 to 300 km up near the poles. Oxygen there glows green and red; nitrogen glows blue and purple.",
    reward: 150,
    test: (e) => e.type === 'aurora',
  },
  {
    id: 'shower',
    field: 'astronomy',
    title: 'A meteor shower',
    text: 'Watch a meteor shower through the telescope (late on a clear night, when the board says one is on)',
    learn: "A shower comes when the Earth crosses the trail of dust a comet left behind. The meteors seem to fly out of one point, the radiant, because the grains travel side by side, like snow in a car's headlights.",
    reward: 250,
    test: (e) => e.type === 'shower',
  },
  {
    id: 'meteorite',
    field: 'astronomy',
    title: 'A stone from space',
    text: 'Find a meteorite where a fireball came down',
    learn: 'A meteor is the streak of light; a meteorite is the stone that reaches the ground. Most are pieces of asteroids, older than any rock on Earth: about 4.6 billion years.',
    reward: 200,
    test: (e) => e.type === 'meteorite',
  },
  {
    id: 'scale',
    field: 'astronomy',
    title: 'How big space is',
    text: 'Walk the solar system: all 9 signs of the scale model on the Lighthouse Road',
    learn: 'At the model’s scale the Sun is a ball 19 cm across and the Earth a grain 1.7 mm across, 20 m away; Neptune is 600 m down the road. The nearest star would be about 5,400 km away.',
    reward: 150,
    test: (e) => e.type === 'solarwalk' && e.count >= 9,
  },
  // ------------------------------------------------------------ physics
  {
    id: 'tesla',
    field: 'physics',
    title: 'The man who lit the world',
    text: "Read Nikola Tesla's plaque at the memorial by Bear Falls",
    learn: 'Two or more alternating currents, each a little behind the other, make a magnetic field that turns by itself. Tesla’s induction motor and his three-phase system still drive most of the world’s machines.',
    reward: 100,
    test: (e) => e.type === 'tesla',
  },
  {
    id: 'coil',
    field: 'physics',
    title: 'Light without wires',
    text: 'Run the Tesla coil in the coil house at Bear Falls',
    learn: 'Two coils tuned to the same frequency pass energy back and forth and build up a very high voltage. The quickly changing field lights a gas-filled tube with no wire to it.',
    reward: 150,
    test: (e) => e.type === 'coil',
  },
  {
    id: 'hydro',
    field: 'physics',
    title: 'Power from falling water',
    text: 'Read the Bear Falls Hydro board at the rim of the gorge',
    learn: 'Power = water’s density × gravity × flow × drop × efficiency. Bear Falls’ 14 m drop and 2.6 m³ of water a second make about 300 kW, as much as about 250 homes use.',
    reward: 120,
    test: (e) => e.type === 'hydro',
  },
  {
    id: 'drag',
    field: 'physics',
    title: 'The wall of air',
    text: 'Reach 250 km/h in the race car hidden in the forest',
    learn: 'Air pushes back harder the faster you go: drag grows with the square of the speed, and the power to beat it with the cube. Twice as fast takes eight times the power.',
    reward: 200,
    test: (e) => e.type === 'racerSpeed' && e.kmh >= 250,
  },
  {
    id: 'lift',
    field: 'physics',
    title: 'Flying on a wing',
    text: "Fly Gus's paraglider off a high edge",
    learn: 'A wing tilted to the air turns the passing air downward, and pushing air down pushes the wing up. Rising warm air, a thermal, can carry you higher than where you started.',
    reward: 150,
    test: (e) => e.type === 'flight',
  },
  // ------------------------------------------------------------ the earth
  {
    id: 'granite',
    field: 'earth',
    title: 'How granite is made',
    text: 'Take a rock sample on top of the big Granite Tor',
    learn: 'Granite cooled slowly from molten rock deep underground, so its crystals had time to grow big enough to see: pink feldspar, grey quartz and black mica. Tors stand where frost and water stripped away the weaker rock round them.',
    reward: 150,
    test: (e) => e.type === 'sample',
  },
  {
    id: 'glacier',
    field: 'earth',
    title: 'A glacier calving',
    text: 'Watch the glacier drop ice into Glacier Lake',
    learn: 'A glacier is snow pressed into ice over hundreds of years, flowing downhill under its own weight. Where it meets water its front cracks and falls in. The lake is milky blue with rock the ice has ground to flour.',
    reward: 150,
    test: (e) => e.type === 'calving',
  },
  {
    id: 'springs',
    field: 'earth',
    title: 'Hot water from the deep',
    text: 'Soak in the hot pool at Steaming Springs',
    learn: 'Rain and snowmelt sink through cracks in the rock, are heated by hot rock kilometres down and rise again along a fault. The deeper the water goes, the hotter it comes back.',
    reward: 100,
    test: (e) => e.type === 'soak',
  },
  // ------------------------------------------------------------ biology
  {
    id: 'salmon',
    field: 'biology',
    title: "The salmon's journey",
    text: 'Catch a Pacific salmon: a sockeye, king, coho, pink or chum',
    learn: 'Salmon hatch in fresh water, grow up at sea and swim back to the stream they were born in, finding it by smell, to spawn once and die. Their bodies feed the bears, the eagles and the forest itself.',
    reward: 100,
    test: (e) => e.type === 'catch' && SALMON.includes(e.fish?.species),
  },
  {
    id: 'bear',
    field: 'biology',
    title: 'A fat bear',
    text: 'Photograph a bear (from a safe distance)',
    learn: 'A grizzly can eat dozens of salmon a day in late summer, building up the fat it lives on through the five or more months of its winter sleep.',
    reward: 150,
    test: (e) => e.type === 'photo' && (e.id === 'bear' || e.id === 'blackbear'),
  },
  {
    id: 'birds',
    field: 'biology',
    title: 'Birds of the north',
    text: 'Photograph a bald eagle',
    learn: 'Bald eagles gather on Alaska’s rivers when the salmon run. Their nests, used year after year, can weigh more than a tonne.',
    reward: 120,
    test: (e) => e.type === 'photo' && e.id === 'eagle',
  },
  // ------------------------------------------------------------ life beyond
  {
    id: 'visitor',
    field: 'life',
    title: 'A visitor from the sky',
    text: 'Find out what came down after the meteor shower',
    learn: 'Life as we know it needs liquid water, a source of energy and carbon chemistry. Astronomers have found thousands of planets round other stars, and look for ones at the right distance from their star for water to stay liquid.',
    reward: 300,
    test: (e) => e.type === 'visitor',
  },
  {
    id: 'extreme',
    field: 'life',
    title: 'Life at the edges',
    text: 'Take your companion from the sky to the hot pool at Steaming Springs',
    learn: 'Microbes live in boiling springs, in Antarctic ice and in rock kilometres down. If life manages here, it might on Mars under the ground, or in the ocean under the ice of Jupiter’s moon Europa.',
    reward: 250,
    test: (e) => e.type === 'soak' && e.companion,
  },
];

export function scienceDone(state) {
  return SCIENCE.filter((o) => state.science && state.science[o.id]).length;
}
