// What the announcer says, by moment, with how often each line comes up.
// The game's voice has a recording of each (tools/voice); a line added here
// needs the voice made again, or it falls back to the device's voice.
export const LINES = {
  fishOn: [['FISH ON!', 5], ['FISH ON! FISH ON!', 2], ['HOOKED UP!', 1], ['GOT ONE!', 1]],
  bigOne: [["IT'S A BIG ONE!", 3], ['MONSTER ON THE LINE!', 1], ['HOLD ON TIGHT!', 1]],
  jump: [["IT'S JUMPING!", 2], ['LOOK AT IT GO!', 1], ['AIRBORNE!', 1]],
  threwHook: [['IT THREW THE HOOK!', 1]],
  hookOff: [['OH NO, THE HOOK CAME OFF!', 2], ['OH NO! IT SHOOK THE HOOK!', 1]],
  snap: [['SNAP! THE LINE BROKE!', 2], ['OH NO! IT BROKE OFF!', 1]],
  spooled: [['SPOOLED! IT TOOK ALL YOUR LINE!', 1]],
  gotAway: [['IT GOT AWAY!', 1]],
  missed: [['TOO SLOW!', 2], ['MISSED IT!', 1]],
  early: [['TOO EARLY!', 1]],
  perfect: [['PERFECT CAST!', 1]],
  backlash: [["BIRD'S NEST!", 1]],
  landed: [['NICE FISH!', 3], ['LANDED!', 2], ['WHAT A CATCH!', 1], ['BEAUTIFUL!', 1]],
  newSpecies: [['NEW SPECIES!', 1]],
  best: [['PERSONAL BEST!', 1]],
  legend: [['LEGENDARY!', 1]],
  bite: [['THE BITE IS ON!', 1]],
  eagle: [['AN EAGLE STOLE IT!', 1]],
  bear: [['LOOK OUT!', 1]],
  bullseye: [['BULLSEYE!', 1]],
  photo: [['WHAT A SHOT!', 2], ['FRAME IT!', 1]],
  treasure: [['TREASURE!', 1]],
  glider: [['A PARAGLIDER!', 1]],
  key: [['A SECRET KEY!', 1]],
  jobDone: [['CHA-CHING!', 2], ['JOB DONE!', 1]],
  bigfoot: [['BIGFOOT?!', 1]],
  racer: [['A FORMULA ONE CAR!', 1]],
  speed: [['FLAT OUT!', 2], ['WHAT A SPEED!', 1]],
  fireball: [['A FIREBALL!', 2], ['LOOK AT THE SKY!', 1]],
  meteorite: [['A METEORITE!', 2], ['A PIECE OF SPACE!', 1]],
  iss: [['THE SPACE STATION!', 1]],
  storm: [['NORTHERN LIGHTS!', 1]],
  scope: [['NEW IN THE SKY LOG!', 1]],
  planets: [['ALL FIVE BRIGHT PLANETS!', 1]],
  topout: [['TOPPED OUT!', 2], ['WHAT A CLIMB!', 1], ['ON TOP OF THE WORLD!', 1]],
};
